[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = 'lts'
python = ['3.10', '3.11']
go = 'latest'
rust = 'latest'
github-cli = 'latest'
terraform = 'latest'
awscli = "latest"
