return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.colorscheme.dracula" },
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  { import = "astrocommunity.color.tint-nvim" },
  -- { import = "astrocommunity.bars-and-lines.heirline-mode-text-statusline/" },
  -- { import = "astrocommunity.diagnostics.trouble-nvim" },
  -- { import = "astrocommunity.editing-support.neogen" },
  -- { import = "astrocommunity.editing-support.zen-mode-nvim" },
  -- { import = "astrocommunity.editing-support.treej" },
  -- { import = "astrocommunity.editing-support.nvim-regexplainer" },
  -- { import = "astrocommunity.editing-support.refactoring-nvim" },
  -- { import = "astrocommunity.editing-support.todo-comments-nvim" },
  -- { import = "astrocommunity.indent.mini-indentscope" },
  -- { import = "astrocommunity.indent.indent-blankline-nvim" },
  -- { import = "astrocommunity.media.presence-nvim" },
  { import = "astrocommunity.pack.python" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.rust" },
  -- { import = "astrocommunity.pack.go" },
  -- { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.java" },
  -- { import = "astrocommunity.motion.harpoon" },
  -- { import = "astrocommunity.motion.leap-nvim" },
  -- { import = "astrocommunity.motion.mini-move" },
  { import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
  { import = "astrocommunity.markdown-and-latex.vimtex" },

}
